# This file is part of riemann-runit.
# https://github.com/kensho/riemann-runit

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Ashok Rao <ops@kensho.com>

language: python

python:
    - "2.7"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
